### ISSUE TITLE
Unable to use britney with methods using email addresses in payload params (seafile API)

### ISSUE THREAD

**Issue by finkyseb** [agrausem/britney#2]
- [description file](http://rest-api.u-strasbg.fr/seafile/description.json)
- method  : share_link_send_mail
- payload params : token, email, extra_msg

I can use this method via the Chrome Advanced REST client with this header value : Content-Type: application/x-www-form-urlencoded.

in my source code : 
client.share_link_send_mail(payload={'token':'8096361af2','email':'any@mail.com','extra_msg':'My very cool link'})

**Comment by agrausem** [comment]
In your description file, the `share_link_send_mail` method has a bad path configuration.
`"path": "api2/send-share-link/"` is used instead of `"path": "/api2/send-share-link/"`. The leading `/` is missing.

If this does not solve your problem, can you send me your global configuration, i.e the middlewares that you enable to post data to this function ?

**Comment by finkyseb** [comment]
Here you can find a minimal exemple of source code which give me :

SporeMethodStatusError: Error 400



Le ven. 27 janv. 2017 à 15:37, Arnaud Grausem <notifications@github.com> a
écrit :

**Comment by finkyseb** [comment]
The issue is due from Seafile API which uses 2 payload parameters formats.
`JSON vs data form (application/x-www-form-urlencoded)`
